In [6]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr ,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [14]:
import numpy as np
import time
#time
#execution performance
size = 1_00_00_00
#python list 
py_list = list(range(size))
start= time .time()
sq_list =[ x**2 for x in py_list]
end = time .time()
print(f"python list ={end-start} second")
#numpy arrays
np_arr=np.array(py_list)
start = time.time()
#vectorisation
sq_array = np_arr**2
end= time.time()
print(f"numpy array time = {end -start} seconds")

python list =1.7813565731048584 second
numpy array time = 0.07552480697631836 seconds


In [18]:
import numpy as np
import sys
#memory
print(f"python list size ={sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy array size = {np_arr.nbytes} bytes")



python list size =8000056000000 bytes
numpy array size = 8000000 bytes


In [25]:
import numpy as np

# create - from lists
arr = np.array([1,2,3,4,5,6])
arr2 = np.array([1,3,6,7,8,"Harshita"])
print(arr2,type(arr2))#dtype print data type
# shape print dimension
print(arr, type(arr))
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[8,4,6]])
print(arr2D , arr2D .shape)

['1' '3' '6' '7' '8' 'Harshita'] <class 'numpy.ndarray'>
[1 2 3 4 5 6] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [8 4 6]] (4, 3)


In [38]:
import numpy as np
#create
arr1 = np.zeros((2,3),dtype ="int64") #prefil with zero value
print(arr1 , arr1.shape)

arr2 = np.ones((6))#prefil 
print(arr2 , arr2.shape)

arr3 = np.full((3,4) , 100)#prefil with value
print(arr3,arr3.shape)

arr4 = np.eye((4)) # used identity matrix create
print(arr4,arr4.shape)

#range(start, end, step)
arr5 = np.arange(1, 10,2)
print(arr5, arr5.shape)

arr6 = np.linspace(1,100 ,4)#evenly spaced arrays
print(arr6 , arr6.shape)




[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1. 1.] (6,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [46]:
#propeties of numpy array
arr= np.array([[1,2,3,4],[3,4,5,6] ,[3,5,6,7]])
print (arr.shape) # dimension = m*n
print(arr.size) #print total elements
print(arr.dtype)
print(arr.ndim)#no of dimension

float_arr =arr.astype(np.float64) # changing type
print(float_arr , float_arr.dtype)

(3, 4)
12
int64
2
[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [3. 5. 6. 7.]] float64


In [51]:
#operation on arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr , arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped , reshaped.shape)

flattend = arr.flatten() # 2D covert into 1D array
print(flattend ,flattend.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [57]:
#indexing
arr = np.array([2,3,4,5,6,7]) #1D array
print(arr[0])
print(arr[3])

arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][2])

#fancy indexing
arr = np.array([1,2,3,4,5])

idx  = [0,1,3]
print(arr[idx])


#boolean indexing
arr = np.array([1,2,3,4,5,6])
print(arr[arr > 2])
print(arr[arr%2 == 0]) #even no case 
print(arr[arr % 2!=0]) # odd no case



2
5
3
[1 2 4]
[3 4 5 6]
[2 4 6]
[1 3 5]


In [63]:
#slicing
arr = np.array([1,2,3,4,5])
#[Start , end , step]
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2]) #kitne element ko skip krna chahte hai
print(arr[:])
    




[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]
[1 2 3 4 5]


In [68]:
# copy vs view
nums = [1,2,3,4,5]
sub_list = nums[1:3] # indexing printing
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3] .copy()
print(sub_arr)# [2,3]

sub_arr[0] =200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[1 2 3 4 5]


In [78]:
#Data type
arr = np.array([1,2,3,4,5 ])
print(arr, arr.dtype)

arr1 = np.array([3+5j])
arr2 = np.array([4+9j])
print(arr1, arr1.dtype)
print(arr1+arr2)


arr = np.array(["prime" ,  {1,2,3}, 3.14])
print(arr ,arr.dtype)
               

[1 2 3 4 5] int64
[3.+5.j] complex128
[7.+14.j]
['prime' {1, 2, 3} 3.14] object


In [84]:
#multi Dimensional Arrarys
arr2D = np.array([[1,2,3] , [4,5,6], [7,8,9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_columns = np.sum(arr2D , axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D , axis = 1)
print(sum_of_rows)

print(arr2D [0:2 , 1:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [96]:
#3D array

arr3D = np.array([[[1,2] , [3,4] ,[5,6] ,[7,8] ,[9,10]  , [11,12]]]) #  2*3*2

print(arr3D , arr3D.shape)
#indexing
print(arr3D[0,1,0])

#slicing
print(arr3D[:,0, :]) # first row from both layers

print(arr3D)




[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]] (1, 6, 2)
3
[[1 2]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]


In [99]:
#Vectorization

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1**2)
print(arr1 +10)
print(arr1+arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [102]:
#Broadcasting

#print(arr+5)
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5] , [1,2,3,4,5]])

print(arr.shape)
print(arr2.shape)

print(arr+arr2)


(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [108]:
#vector Normalization

arr = np.array([[1,2] ,[3,4]])

print(np.mean(arr)) # mean value print
print(np.std(arr))#standard deviation print

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr - mean)/std_dev
print(normalized_arr)
print(mean)
print(std_dev)
print(np.sqrt(5/4))

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


In [113]:
#Mathematical function

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.argmin(arr))#return minimum value index
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
0
4
3.0
1.4142135623730951
3.0
2.0


In [115]:
#Power function

arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr , 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [118]:
#logrithmic function

arr = np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [123]:
#Rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

3.0
4.0
3.0
3.0


In [125]:
# Extra function

arr = np.array([1,2,3,8,4,5])

print(np.unique(arr))
print(np.abs(arr))
print(np.sort(arr))

[1 2 3 4 5 8]
[1 2 3 8 4 5]
[1 2 3 4 5 8]
